language: generic

services:
  - docker

env:
  global:
    - FILENAME='CV_Davide_Fauri'
  jobs:
    - LANGUAGE='italian' SHORTLANG='ita'
    - LANGUAGE='english' SHORTLANG='eng'

script:
  - cat $FILENAME.tex | sed 's|^\\usepackage\[[a-z,=]*\]{babel}|\\usepackage\['"$LANGUAGE"'\]{babel}|' > $FILENAME-$SHORTLANG.tex
  - ls -al *.tex
  - cat $FILENAME-$SHORTLANG.tex | grep babel
  - docker run --mount src=$TRAVIS_BUILD_DIR,dst=/usr/src/tex,type=bind dxjoke/tectonic-docker
    /bin/sh -c "tectonic --keep-intermediates --reruns 0 $FILENAME-$SHORTLANG.tex; biber $FILENAME-$SHORTLANG; tectonic --reruns 1 $FILENAME-$SHORTLANG.tex"

deploy:
  provider: releases
  edge: true
  api_key:
    secure: zViR6NjO9VG1sy+SJ7WHjr/Y+ZvRNW6yNzcCL9nHCMtqMTypzwiR1o9tSHg/ywME/WbgSP7sBuHVpKkCvFkXYxpzFSEj3I8CeHGdz22kwAPBe6X/0H8P85OHz/NV+nsCSLPXOk3UrzjdWLuZ8xoBfXwhwp71y8Xiu3hmbbPvkMShuNnCpjahwvzBeQJUab+DoqBpNjQwOxawAtFEH1PG4dAj5XFgGTYVyATUzvSKM/praGvKO5CAhmAsVE1KN4ofHLwM2/c+c/nJll90pxJhHX6ZMxs+EES8XHOMPuZD5nt+6h0gdQfOL/d/Q8KiNtwhVx4SOZ69WfifTNQgYWyS5n5AW2oLXnnhU59zNSbqPSdvCVPl8ZrtPE4m5wCNpzSst4LuGDGVMeBL8W5m6iCJ9dxE1SaV/C9kZYcCqbyy5e4RMp1B3xHL7Cj88eV1fmP7bbllFKJExK3NOhmEWG47ajFLwpo1nbG/EQjXJhTYbo/eXC86dgRTTJi5v9uYS5hHSIsdwGKxZVWEWrbDnPHLwyYBQXqvh79rUt/+5Cf6fUSMRf1sGbtGpcMmWQguGq+MDK8jmsM8MC7jj3AjngoITr0wiq99Zgxf/3EkCUvC6lFJOAy4sZMpRpWdR2/Xry/ByWH3h27yv0EVkEpVvXu6/+nz36bsjO8wwfKRL0bk7pI=
  file_glob: true
  file:
    - $FILENAME-$SHORTLANG.pdf
  on:
    tags: true
    all_branches: true
