language: generic

addons:
  apt:
    update: false
    packages:
      # to read from PDFs
      - ghostscript
      # needed for makeindex
      - texlive-binaries

cache:
  directories:
  - "$HOME/.cache/Tectonic"
  - "$HOME/miniconda"

env:
  global:
    - MAGICK_CONFIGURE_PATH=$HOME/.config/ImageMagick

before_install:
  # Edit ImageMagick policy to read PDF and write PNG
  - echo $MAGICK_CONFIGURE_PATH
  - mkdir -p $MAGICK_CONFIGURE_PATH
  - echo '<policymap>' > $MAGICK_CONFIGURE_PATH/policy.xml
  - echo '<policy domain="coder" rights="read" pattern="PDF" />' >> $MAGICK_CONFIGURE_PATH/policy.xml
  - echo '</policymap>' >> $MAGICK_CONFIGURE_PATH/policy.xml
  - sudo rm /etc/ImageMagick-6/policy.xml

install:
  # Needed to check if conda already installed
  - export PATH="$HOME/miniconda/bin:$PATH"

  # If not yet installed, obtain Miniconda and tectonic
  - if ! command -v conda > /dev/null; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda -u;
      conda config --add channels conda-forge;
      conda config --set always_yes yes;
      conda install tectonic==0.1.11;
    fi

  # Install biber if required for compiling the references.
  # Biber version should match the biblatex version of Tectonic
  - conda install -c malramsay biber==2.11 --yes
  - conda info -a

script:
- make resume


deploy:
  provider: releases
  api_key:
    secure: AAmoHOP8ivKVhhYAhzMJk/ipvm+tzFmCu1T++oeLEHSkln2oY8cuVxeux+5r7bgwqRIuDvyUoyMg0pgQU41avP4sAzvdZ5P8l6U112iU6oe59LyUTm1DYjfmdD6aCKFc1B56s9TJS+R2aAG1yQNV8dWGCXtxdQwaD/SYpx8AI+y+uS/gP7qBwN2Nd3PYxvcRYLV3D9Xja5NSdak2m1kjaohfs4TzhOiqU+60yEVRmcGt+M+36Dy8LMJO0zoHCN6iVF0+Qn/eROQVNBap1hhADha59fS5CEaZDWZCn/S0IN0Lbm70KhxOcb7BE7T78bX48WiFpZ8ThE48ovy9JO9hgIYgmpTAyOQHhLdzqfV04+Iyy4pSYEXsYe1bwcnGGxNqRu76Jt8DWawh55s26S9zDXDsBG7Qjvjj4+E8kQq8Qkw4OIFa7MpshfLjxW9M7WV2l/LMwOamDBsjF7nhq9XnE297NdSXpH/lvFOASwC9Aa7OZGhwtHt1V+lo5U+8DIEDqjZZGtWtidIKfrLQRjl7QwQxIKnkPMYz7sOHREs3+BSGJWrjogvSfO3y67ZKUw1gU7nD36jDk3g8QSpgWv0MgTRH6GG+OcfG23L1g3PxJgWjkeWNMXpXxWQ7JXxH66M7FhQjbGD/12CiIeFALgDZ62ieClfFl7zfPjpKlxFtbvM=
  file_glob: true
  file:
    - CV_*.pdf
    # - CV_*_eng*.png
  on:
    tags: true
    all_branches: true
  skip_cleanup: true
