language: generic

cache:
  directories:
  - "$HOME/.cache/Tectonic"
  - "$HOME/miniconda"

before_install:
  # Install makeindex, if you do not use an index you can remove this (also remove the extra makeindex call).
  # - sudo apt-get install texlive-binaries

install:
  # Needed to check if conda already installed
  - export PATH="$HOME/miniconda/bin:$PATH"

  # If not yet installed, obtain Miniconda and tectonic
  - if ! command -v conda > /dev/null; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda -u;
      conda config --add channels conda-forge;
      conda config --set always_yes yes;
      conda install tectonic==0.1.11;
    fi

  # Install biber if required for compiling the references.
  # Biber version should match the biblatex version of Tectonic
  - conda install -c malramsay biber==2.11 --yes
  - conda info -a

script:
- make


deploy:
  provider: releases
  api_key:
    secure: RoJ10tNqYOk6K7yxiXT4nj8oDocr9fnsWi9cQzqe5/jkCXquR6eT92DXq4vLdmc7uHWOFjwP1iURDs61upqEdbmLki8XMiZ5rXAtxWBF04je+TDUS4eLnc8abf6E/jJj4HX9c84SqVFl9aePyPZinm8QDvxw722vYOqAyeNbsz8MZVVFQvUvzmWwYbD1/iNkZ5v7IrfKdHPFi5TTOARGI1DI/D63pa2TzPsoh2lCSqe+t8IIY2gx7QR4HCCdEeBBqaABwm66La+7PjLl2HNk8c+VSrgParOV67HVZDCYSqokSgykZTausem06+LkYP62JBOxldNYchTluj+1NEctn2Bktk7jfLocl6LfcD3MOqpYa5XPha3WmaLpVOx0G/8cQ+L7JBT7DlqEzuhjntXaJH7g2cB0IYAnP7ofVYHJeNgqlKqyerx7HkpJ2/6W6XJMGbfcbul1dG555jYCtn0nkowYnunzY7PrxCtqJReWIeQDTpKsiFCtoATjk0ylRC9J/cgK+jTka2kYuQhk/NSkmHpodIJh199df9MPsuo2ibjkKBjNtY7SRjpMqDe9HI2JTdfLFAZ6Yg/Lu1GJsrVtdogQLf6ov4JS902mFO0fQpPkK7o5EhE5ZWKhZ8wJP1OQNszPYQx/V/iEVNb3HSXDYDyA/PNMdZEkf+WhskWjFE0=
  file_glob: true
  file: CV_*.pdf
  skip_cleanup: true
  on:
    tags: true
